// <auto-generated />
using Database.Model.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20201207000941_m2")]
    partial class m2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("Database.Model.Entity.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Start")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Race");
                });

            modelBuilder.Entity("Database.Model.Entity.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CurrentTime")
                        .HasColumnType("REAL");

                    b.Property<double>("DistanceToFinish")
                        .HasColumnType("REAL");

                    b.Property<double>("HeavyMalfunctionProbability")
                        .HasColumnType("REAL");

                    b.Property<double>("LightMalfunctionProbability")
                        .HasColumnType("REAL");

                    b.Property<double>("RandomNumber")
                        .HasColumnType("REAL");

                    b.Property<double>("Speed")
                        .HasColumnType("REAL");

                    b.Property<string>("TeamName")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeForFixing")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TimeSpentOnFixingRest")
                        .HasColumnType("REAL");

                    b.Property<int>("TypeOfVehicles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleManufacturingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleModel")
                        .HasColumnType("TEXT");

                    b.Property<int>("vehicleState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Database.Model.Entity.VehicleRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Start")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VehicleRace");
                });
#pragma warning restore 612, 618
        }
    }
}
